import type { Customer } from "./types";

const firstNames = [
  "James",
  "Mary",
  "John",
  "Patricia",
  "Robert",
  "Jennifer",
  "Michael",
  "Linda",
  "William",
  "Elizabeth",
  "David",
  "Barbara",
  "Richard",
  "Susan",
  "Joseph",
  "Jessica",
  "Thomas",
  "Sarah",
  "Charles",
  "Karen",
  "Christopher",
  "Nancy",
  "Daniel",
  "Lisa",
  "Matthew",
  "Betty",
  "Anthony",
  "Margaret",
  "Mark",
  "Sandra",
  "Donald",
  "Ashley",
  "Steven",
  "Kimberly",
  "Paul",
  "Emily",
  "Andrew",
  "Donna",
  "Joshua",
  "Michelle",
  "Kenneth",
  "Carol",
  "Kevin",
  "Amanda",
  "Brian",
  "Dorothy",
  "George",
  "Melissa",
  "Timothy",
  "Deborah",
  "Ronald",
  "Stephanie",
  "Edward",
  "Rebecca",
  "Jason",
  "Sharon",
  "Jeffrey",
  "Laura",
  "Ryan",
  "Cynthia",
  "Jacob",
  "Kathleen",
  "Gary",
  "Amy",
  "Nicholas",
  "Angela",
  "Eric",
  "Shirley",
  "Jonathan",
  "Anna",
  "Stephen",
  "Brenda",
  "Larry",
  "Pamela",
  "Justin",
  "Emma",
  "Scott",
  "Nicole",
  "Brandon",
  "Helen",
  "Benjamin",
  "Samantha",
  "Samuel",
  "Katherine",
  "Raymond",
  "Christine",
  "Gregory",
  "Debra",
  "Frank",
  "Rachel",
  "Alexander",
  "Catherine",
  "Patrick",
  "Carolyn",
  "Jack",
  "Janet",
  "Dennis",
  "Ruth",
  "Jerry",
  "Maria",
];

const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Gutierrez",
  "Ortiz",
  "Morgan",
  "Cooper",
  "Peterson",
  "Bailey",
  "Reed",
  "Kelly",
  "Howard",
  "Ramos",
  "Kim",
  "Cox",
  "Ward",
  "Richardson",
  "Watson",
  "Brooks",
  "Chavez",
  "Wood",
  "James",
  "Bennett",
  "Gray",
  "Mendoza",
  "Ruiz",
  "Hughes",
  "Price",
  "Alvarez",
  "Castillo",
  "Sanders",
  "Patel",
  "Myers",
  "Long",
  "Ross",
  "Foster",
  "Jimenez",
];

const countryCodes = [
  { code: "+57", country: "CO" },
  { code: "+1", country: "US" },
  { code: "+52", country: "MX" },
  { code: "+34", country: "ES" },
  { code: "+54", country: "AR" },
  { code: "+56", country: "CL" },
  { code: "+51", country: "PE" },
  { code: "+55", country: "BR" },
  { code: "+593", country: "EC" },
  { code: "+58", country: "VE" },
];

const statuses: Array<"active" | "inactive" | "pending"> = [
  "active",
  "inactive",
  "pending",
];

const generateCustomer = (index: number): Customer => {
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
  const countryCodeData =
    countryCodes[Math.floor(Math.random() * countryCodes.length)];
  const status = statuses[Math.floor(Math.random() * statuses.length)];

  // Generar fecha de cliente desde (entre 2020 y 2024)
  const customerSinceDate = new Date(
    2020 + Math.floor(Math.random() * 5),
    Math.floor(Math.random() * 12),
    1 + Math.floor(Math.random() * 28)
  );

  // Generar fecha de actualización (entre la fecha de creación y hoy)
  const updatedAtDate = new Date(
    customerSinceDate.getTime() +
      Math.random() * (Date.now() - customerSinceDate.getTime())
  );

  const numberOfOrders = Math.floor(Math.random() * 50) + 1;
  const totalOrders = Math.floor(Math.random() * 50000000) + 100000; // Entre 100,000 y 50,100,000 COP

  // Generar número de teléfono
  const phone = `${Math.floor(Math.random() * 900) + 100}-${
    Math.floor(Math.random() * 9000) + 1000
  }`;

  return {
    id: `CUS-${String(index + 1).padStart(3, "0")}`,
    customerName: `${firstName} ${lastName}`,
    email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}${index}@example.com`,
    countryCode: countryCodeData.code,
    phone: phone,
    numberOfOrders: numberOfOrders,
    totalOrders: totalOrders,
    customerSince: customerSinceDate.toISOString().split("T")[0],
    status: status,
    updatedAt: updatedAtDate.toISOString().split("T")[0],
  };
};

export const customerList: Customer[] = Array.from({ length: 100 }, (_, i) =>
  generateCustomer(i)
);
